### ISSUE TITLE
Strange +add issue

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/menus#11]
Here"s part of the menu I'm building.

```
        $menu->add('HR', 'school');
        $menu->school->add('Employees', 'employees');
```

This will error out with

```
Call to a member function add() on a non-object
```

However this works

```
        $menu->add('School', 'school');
        $menu->school->add('Employees', 'employees');
```

I could figure out why this was Happening until I realized that the Route and Link name have to be the same.

Is this a bug?

**Comment by kaidesu** [comment]
No no, you got it kinda backwards!

Your second example is correct; your first example should be:

``` php
$menu->add('HR', 'school');
$menu->hr->add('Employees', 'employees');
```

It's going off the _name_ of the menu item (in lower case form) - not the route/URL.

**Comment by illuminate3** [comment]
Thanks!
