### ISSUE TITLE
feature request: ability to add id="some.id.name" to link

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/menus#16]
```
        $menu->add('Categories',
            array(
                'class' => '',
                'id' => 'showLeft'
            ))
            ->link->href('#');
```

The above won't show class or id in the html link.

I'm not sure if this is a bug or feature request.

**Comment by kaidesu** [comment]
I spent some time cleaning the attribute functionality up today. Your code will work, you just need to echo out the attributes within your view partial for your menu:

``` html
{!! $item->attributes() !!}
```

See the documentation [here](https://github.com/caffeinated/menus/wiki/Attributes) for more information, and let me know if you run into any issues or have questions!
