### ISSUE TITLE
Argument 3 passed to Caffeinated\Menus\Menu::__construct() must be an instance of Collective\Html\HtmlBuilder, instance of Illuminate\Html\HtmlBuilder given

### ISSUE THREAD

**Issue by od3n** [caffeinated/menus#18]
I got this error when trying to setup menus.

`Undefined variable: menu_example`

I followed all the instructions, am I missing something?

**Comment by od3n** [comment]
same issue #7 ?

**Comment by od3n** [comment]
Sorry, my bad. I miss the step to register new MenuServiceProvider.

After added, i'm getting this error

`Argument 3 passed to Caffeinated\Menus\Menu::__construct() must be an instance of Collective\Html\HtmlBuilder, instance of Illuminate\Html\HtmlBuilder given, called in /home/vagrant/Git/rms/vendor/caffeinated/menus/src/Caffeinated/Menus/MenusServiceProvider.php on line 47`

**Comment by od3n** [comment]
Possible patch? It's working for me
https://github.com/AgusCT/menus/commit/79d803022e159b095691136da66002f87c438af0

**Comment by kaidesu** [comment]
The Collective Html package was used on purpose, as the Illuminate Html package is no longer supported or maintained officially by Laravel (e.g. Taylor).

http://laravelcollective.com/about
