### ISSUE TITLE
Invalid <li> syntax

### ISSUE THREAD

**Issue by Propaganistas** [caffeinated/menus#22]
Hi

Please take a look at the attached image.
Using the `asUl()` method it seems that an empty tag attribute (both attribute name and value) is being injected into each `li` element.

I haven't looked at the code, but I expect that this can be solved by simply inserting an if-empty statement when looping over any additionally set attributes.

![schermafbeelding 2015-04-23 om 19 38 30](https://cloud.githubusercontent.com/assets/6680176/7303356/59fd2ea0-e9f0-11e4-8da9-cf6c1639eb36.png)

**Comment by kaidesu** [comment]
Thanks for pointing this out, I'll take a look into it~

**Comment by kaidesu** [comment]
@Propaganistas If you're able to, pull in the latest dev release through Composer and give it another run to verify that the issue has been fixed on your end!

**Comment by Propaganistas** [comment]
Fixed indeed.
Thanks for the quick follow up!

**Comment by kaidesu** [comment]
Good to hear~ And no problem :+1:
