### ISSUE TITLE
Show children only

### ISSUE THREAD

**Issue by xtrasmal** [caffeinated/menus#23]
I've got a menu at the top of the site and want the children to be show on a sidebar.
Is it possible to show the children only?

**Comment by kaidesu** [comment]
Yup~

There's two methods you can call on a menu item; `hasChildren()` which will return a `bool` based on if it has children items or not, and `children()` which will return an array of all children items that you'll be able to loop through as needed. You can see these methods in use on the wiki [here](https://github.com/caffeinated/menus/wiki/Blade-Bootstrap-Template#itemsbladephp).

You should be able to build a partial to loop through children item within your sidebar.

**Comment by xtrasmal** [comment]
How do I create a menu that has 
- 3 levels deep
- Page titles are more then one words. Like Add user, so not just Blog or Home

**Comment by kaidesu** [comment]
The answer I provided in your other issue https://github.com/caffeinated/menus/issues/20#issuecomment-96081012 answers those two questions.

**Comment by xtrasmal** [comment]
Thank you very much. I got it working.
