### ISSUE TITLE
Add new item from controller

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#27]
Good evening,

how can I add a new menu item to an existing menu instance within the controller ?

Sorry for my bad english. I'm German.

Greetings,

**Comment by kaidesu** [comment]
Sorry, looks like I forgot to write the documentation on this! It's simple though:

**Creating our initial menu:**

``` php
Menu::make('example', function($menu) {
    $menu->add('Link 1', '/link-1');
    $menu->add('Link 2', '/link-2);
});
```

**Somewhere else (in a controller, for instance):**

``` php
$menu = Menu::get('example');

$menu->add('Link 3', '/link-3');
$menu->add('Link 4', '/link-4');
```

**Comment by ghost** [comment]
And from an service provider? It's possible ?

**Comment by ghost** [comment]
Background:

I've use the Skylabs Module Plugin and each modules should have the possibilty to register a menu point. The menu service provider is located in Core Module.

**Comment by ghost** [comment]
Current value is "null". Within the Controller all okay.

**Comment by kaidesu** [comment]
Yes, that is certainly possible (and the best location, imho)! Just be sure that your menu is created _before_ trying to `get()` it and add items to it.

**Comment by ghost** [comment]
Okay, it’s functional.

How can I use sub menu points ?

Von: Shea Lewis [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. April 2015 01:33
An: caffeinated/menus
Cc: virtualstep
Betreff: Re: [menus] Add new item from controller (#27)

Yes, that is certainly possible (and the best location, imho)! Just be sure that your menu is created before trying to get() it and add items to it.

**Comment by ghost** [comment]
I find It out.

Add this please to your doc.

$menu->add('Blog', 'blog');
            $menu->blog->add('Blog 2', 'blog');

**Comment by kaidesu** [comment]
Documentation on adding menu items can be found here now: https://github.com/caffeinated/menus/wiki/Basics-of-Menu-Items
