### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#28]
Hello,

I want to create a breadcrumb with your menu plugin.

Can I do this easily ? 

Greetings.

**Comment by kaidesu** [comment]
No, the package does not have breadcrumb generation.

**Comment by ghost** [comment]
Do you have a plan for this ?

Von: Shea Lewis [mailto:notifications@github.com] 
Gesendet: Freitag, 1. Mai 2015 18:09
An: caffeinated/menus
Cc: virtualstep
Betreff: Re: [menus] Breadcrumb (#28)

No, the package does not have breadcrumb generation.

**Comment by kaidesu** [comment]
Not at the moment, and I'm unsure if this package should handle breadcrumb generation. It'd probably be best to create a dedicated package for such a feature.
