### ISSUE TITLE
After filtering menu items, have a clean-up to eliminate empty submenus?

### ISSUE THREAD

**Issue by AlexRegenbogen** [caffeinated/menus#30]
After using a similar approach as stated in https://github.com/caffeinated/menus/issues/26, I'm now one step away from my desired solution.... ;-)

If there are items that are not allowed, they will be removed from the navigation, but any remaining submenus that no longer have any items, are still displayed....

Would be very nice to have some sort of clean-up possibility to remove all items without children and without an link.

**Comment by kaidesu** [comment]
Would that not be something the developer should handle for their specific use-case when filtering?

**Comment by AlexRegenbogen** [comment]
The more I think about it, the more I feel like that's the right answer ;-)

Solved it by adding the clean-up in MyMenu in the make method before passing $menu along to the view...

**Comment by kaidesu** [comment]
:+1:
