### ISSUE TITLE
"&nbsp" breaks HTML layout with icon function

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#31]
Hello,

in the attached screen you will seen a &nbsp; at the end of the icon line.

This breaks my layout and is not correct, when I will only the icon. 

Please correct this.
![2015-05-01 15_35_29-greenshot capture form](https://cloud.githubusercontent.com/assets/10707232/7430805/02c923a4-f018-11e4-9299-10be8b5e661d.png)

**Comment by kaidesu** [comment]
Fixed in v1.0.5~
