### ISSUE TITLE
Active Filter

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#34]
Hi,

a little question:

How can I get only the active menu point ?

Is there a function ?

**Comment by kaidesu** [comment]
What do you mean?

**Comment by ghost** [comment]
Hi,

ok. In my application I need to know, which menu point is current active.

For example

Home ( /home)
Gallery (/gallery) (active)
Images (/images)

With this Information I translate dynamically the page title.

Currently I use for this information a foreach-loop and check, If the item active.

Is here a faster way ? 

The perfect way for me, is addionaly to know, which main and sub menu point is active.

U knwo what i meaN ?

**Comment by kaidesu** [comment]
The package doesn't have this, but would be an easy addition to add. I'll add it to my list of things to do!

**Comment by kaidesu** [comment]
Added with ee7fed8f97d146b9cb24324541e90a0487a3ab3b.

``` php
dd(Menu::get('example')->active());
```

Will return an array of the menu items that are currently active.
