### ISSUE TITLE
Collective\Html\HtmlBuilder Giving Errors

### ISSUE THREAD

**Issue by nla-asia** [caffeinated/menus#35]
Hi , I am getting this error on my laravel5.0.13 new project.Not sure, this is an issue or my setup fault. Please kindly help. 

Argument 3 passed to Caffeinated\Menus\Menu::__construct() must be an instance of Collective\Html\HtmlBuilder, instance of Illuminate\Html\HtmlBuilder given, called in D:\www\laravel-5-boilerplate\vendor\caffeinated\menus\src\Caffeinated\Menus\MenusServiceProvider.php on line 47 and defined

**Comment by nla-asia** [comment]
oh, it looks like i am missing the package : http://laravelcollective.com/docs/5.0/html 
i got it ,now.

**Comment by kaidesu** [comment]
Just to clarify, the Laravel Collective HTML package will be installed with Caffeinated Menus. I'm guessing you already had the Illuminate HTML package installed with your application though?

**Comment by nla-asia** [comment]
yes, Illuminate HTML package is already there( i am using : https://github.com/rappasoft/laravel-5-boilerplate). but Laravel Collective HTML package is not.So, I needed to install it in order to work Caffeinated Menus well.
