### ISSUE TITLE
Bad append and prepend

### ISSUE THREAD

**Issue by myrrc** [caffeinated/menus#38]
Hello. I want to use in my project ->prepend as in the example ( ->prepend('<span class="glyphicon glyphicon-user"></span>') ) as html . But it results into plain text
![2015-05-22 17-39-15](https://cloud.githubusercontent.com/assets/7099650/7772841/c01ae6aa-00b1-11e5-8b8d-440b32245742.png)

**Comment by kaidesu** [comment]
This is because by default, Laravel Blade escapes all data that's passed through. To render the HTML when echoing, use the `{!! !!}` syntax:

``` html
Hello, {!! $name !!}.
```

Read more here: http://laravel.com/docs/5.0/templates#other-blade-control-structures
