### ISSUE TITLE
Class html does not exist

### ISSUE THREAD

**Issue by piperone** [caffeinated/menus#4]
I have no idea if I've done this correctly. Basically, I did as you suggested: Made a new service provider called MenuServiceProvider with two methods - one empty register-method and a boot-method that has the code from the example in your readme (\Menu::make(...)). I then registered it in config/app.php.

Now I just get this:

```
ReflectionException in Container.php line 776:
Class html does not exist
```

**Comment by ParadoxNL** [comment]
By default in Laravel 5.0, Html and Form are not embedded anymore.

Add the following lines in the require section of composer.json file and run composer update "illuminate/html": "5.*"

Register the service provider in config/app.php by adding the following value into the providers array:
'Illuminate\Html\HtmlServiceProvider'

Register facades by adding these two lines in the aliases array:
'Form'=> 'Illuminate\Html\FormFacade', 'HTML'=> 'Illuminate\Html\HtmlFacade'

Source: http://laravel.io/forum/09-20-2014-html-form-class-not-found-in-laravel-5

**Comment by ParadoxNL** [comment]
Coming back on my original answer, after finding out that they use Collective\Html\HtmlServiceProvider. I managed to solve your error by loading this manually in the service providers.

**Comment by kaidesu** [comment]
This is an error on my part though, I believe I'm using the HTML facade directly in the package rather than injecting it where I need it (I'll try to look into it today).

You shouldn't be forced to install a separate package and edit your service providers in this manner.

**Comment by piperone** [comment]
Yea, I saw that the Laravel-Collective-stuff was installed, so I assumed I didn't have to go through the require-illuminate-html-drill. It's a minor issue though, so I'm guessing @kaidesu will have it fixed before long :)

**Comment by ParadoxNL** [comment]
Just register it in the package boot fuction like this: 

``` php
public function boot() {
    $this->app->register('Collective\Html\HtmlServiceProvider');
}
```

And it should work flawlessly.

**Comment by kaidesu** [comment]
@ParadoxNL thanks~

I pushed an update for this: 2820fb848da1c1a8e5aa7f399e52197bff4b67cf per ParadoxNL's suggestion (after checking, I was not referencing any facade directly). Let me know if this fixes your issue and we can get this closed :smile:
