### ISSUE TITLE
Multi-lang

### ISSUE THREAD

**Issue by myrrc** [caffeinated/menus#40]
Hello again. The problem is that menu Items use  Russian(non-latin symbols) and I can not add sub-items to such. Is there a solution to that problem?

**Comment by kaidesu** [comment]
Sorry, you can also assign menu items directly to a variable, as such:

``` php
Menu::make('example', function($menu) {
    $profile = $menu->add('профиль', '#');
    $profile->add('Редактировать профиль', 'profile/edit');
});
```

I'll get this added to the documentation.
