### ISSUE TITLE
Bug: Item Active State don't appear within edit/create

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#42]
Hi,

within https://github.com/caffeinated/menus/issues/32 you build in a method to get current active state via
     $item->data('active')

But when I have a route to edit or create (example users/create) this active state is not set. But main route "users" is active.

Can u fix this ?

**Comment by kaidesu** [comment]
This has already been reported here #25. Rest assured its on my list of updates to make!

**Comment by ghost** [comment]
When u will fix that ?

**Comment by kaidesu** [comment]
I'll probably tackle this this week as I update the package for Laravel 5.1.

**Comment by kaidesu** [comment]
Consolidated this issue into #44.
