### ISSUE TITLE
Active State with AJAX

### ISSUE THREAD

**Issue by ghost** [caffeinated/menus#45]
Hello!

I have currently one url e.g. "backend/".

All links in this layout will load bis ajax (e.g. backend/news)

The menu is definied over your add on.

How can I set here the link how is active ?

Greetings from Germany.

**Comment by kaidesu** [comment]
The active link detection is determined via the URI string. If your content is loading through AJAX, then you'll need to manage the active state yourself.

https://github.com/caffeinated/menus/wiki/Active-Link-Detection

**Comment by ghost** [comment]
How can I do this with your link ?

Have you an example ?
 

Am 15. Juni 2015 10:30:45 schrieb Shea Lewis notifications@github.com:
