### ISSUE TITLE
How to handle Submenu in a different layout position

### ISSUE THREAD

**Issue by mstaack** [caffeinated/menus#56]
lets say i have this menu:

```
Menu::make('main', function ($menu) {
$menu->add('Client', 'client')->prepend('<i class="fa fa-suitcase"> </i> ');
$menu->client->add('Insurance', '/client/insurance');
```

now i have a bootstrap list-group element in my design..
i would like to show the subitems  in this list group..somethin like this:

```
if(currentmenu->hasChilds)
foreach($childs as $item){
{{ link for submenu item}}
}
```

any ideas or hints?

**Comment by mstaack** [comment]
any help for this?

**Comment by kaidesu** [comment]
I'm not sure I understand what you need. An example of how to display menu item children links is in the documentation [here](https://github.com/caffeinated/menus/wiki/Blade-Bootstrap-Template):

``` php
@if($item->hasChildren())
    <ul class="dropdown-menu">
        @foreach($item->children() as $child)
            <li><a href="{{ $child->url() }}">{{ $child->title }}</a></li>
        @endforeach
    </ul>
@endif
```
