### ISSUE TITLE
Is there any way to switch from Collective\Html to Illuminate\Html?

### ISSUE THREAD

**Issue by syahzul** [caffeinated/menus#57]
Since we still can use the official package, can we have some sort of option to switch which HTML package to be use in our app? Right now, I have to change all the HTML package to Collective version if I want to use this package.

**Comment by kaidesu** [comment]
No - `Illuminate\Html` has been deprecated and is no longer maintained, so you should be switching over to Collective~

**Comment by syahzul** [comment]
Ok, nice to know that. Thanks.
