### ISSUE TITLE
Latest laravel breaks package (5.1.24)

### ISSUE THREAD

**Issue by felorhik** [caffeinated/menus#68]
```
Declaration of Caffeinated\Menus\Collection::prepend() should be compatible with Illuminate\Support\Collection::prepend($value, $key = NULL)
```

This shows up when updating to laravel 5.1.24 and loading the library through middleware.

https://github.com/caffeinated/menus/wiki/Quick-Start

is a perfect example of how to recreate this.

**Comment by felorhik** [comment]
https://github.com/laravel/framework/blame/5.1/src/Illuminate/Support/Collection.php#L550

is where the issue is, looks like a simple fix.

**Comment by yajra** [comment]
Adding comment to get notified when PR is merged / issue closed. ^_^ Thanks!
