### ISSUE TITLE
Fatal exception when following "Installation" & "Getting Started" on Wiki

### ISSUE THREAD

**Issue by peterhanneman** [caffeinated/menus#7]
I've copy and pasted each step from the Wiki pages "Installation" & "Getting Started".  As soon as I add `App\Providers\MenuServiceProvider` to my list of providers in `config/app.php` I get `"Call to undefined method Caffeinated\Menus\Facades\Menu::make()".`  Have tried twice with fresh L5 installations to no avail.

**Comment by kaidesu** [comment]
Run `composer update` against your app as I've made a slight bug fix, and then simply make your menu within your `MenuServiceProvider`'s `boot` method rather than the `register` method.

I've updated the Getting Started wiki page as well~

Thanks for pointing this out! Let me know if you run into issues with this so I can take a further look into things.

**Comment by mstaack** [comment]
i still have the same problem? any ideas?

added to providers:     'App\Providers\MenuServiceProvider',
added MenuServiceProvider class to Providers directory..

tried composer update

**Comment by kaidesu** [comment]
@liptonsparkling could you open a new issue with your problem, and give more details on your code?

e.g. steps taken to add the package, how you're creating your menu, the actual error involved, etc.

**Comment by dmcdenissen** [comment]
I've got the same error. (Call to undefined method Caffeinated\Menus\Facades\Menu::make())

- I installed it by using the "Installation" section within the Menus wiki (https://github.com/caffeinated/menus/wiki/Installation)
- Then I commented 'Caffeinated\Menus\MenusServiceProvider' in the config/app.php (providers)
- And added 'App\Providers\MenuServiceProvider' to config/app.php (providers)
- I created the file MenuServiceProvider.php within App/Providers and used the code from the Wiki (https://github.com/caffeinated/menus/wiki/Quick-Start)
