### ISSUE TITLE
Menu sub-items error

### ISSUE THREAD

**Issue by yajra** [caffeinated/menus#78]
It seems like using the latest version (v2.2.1) breaks the menu sub-items where parent menu uses two words or more like below:

``` php
Menu::make('example', function($menu) {
    $menu->add('My Menu', '/espresso');
    $menu->myMenu->add('Americano', '/espresso/americano');
    $menu->myMenu->add('Breve', '/espresso/breve');
    $menu->myMenu->add('Cappuccino', '/espresso/cappuccino');
    $menu->myMenu->add('Latte', '/espresso/latte');
});
```

**Comment by yajra** [comment]
Work around atm, is to bind the parent menu to a variable. Or maybe a better approach than what I am used to be doing.

``` php
Menu::make('example', function($menu) {
    $myMenu = $menu->add('My Menu', '/espresso');
    $myMenu->add('Americano', '/espresso/americano');
    $myMenu->add('Breve', '/espresso/breve');
    $myMenu->add('Cappuccino', '/espresso/cappuccino');
    $myMenu->add('Latte', '/espresso/latte');
});
```

Have updated my menu like this. Up to you if you want to fix this. Just note that it breaks on my installation and maybe others too. ^_^. Thanks!

**Comment by kaidesu** [comment]
D'oh, silly me - I know what's wrong - I'll have this patched in a couple minutes.

**Comment by kaidesu** [comment]
Give v2.2.2 a go.

Slugs will be properly camel cased, e.g. "My Menu" will become "myMenu".

**Comment by yajra** [comment]
Works great! Thanks a lot!
