### ISSUE TITLE
New Feature: Active Link support

### ISSUE THREAD

**Issue by SergeyMiracle** [caffeinated/menus#8]
Would be nice to parse menu with active element (current link).

Didn't find it in wiki or code.

**Comment by kaidesu** [comment]
It's on my list of things to do for the package :+1:

**Comment by SergeyMiracle** [comment]
Nice :+1:

**Comment by pyansopyan** [comment]
so, how to check the link is active?

**Comment by kaidesu** [comment]
The package will now automatically detect the currently active link, and add a new `active` class to the item. Just be sure to echo out your item's attributes from within your view file, and use CSS to make any style changes as needed.

See the documentation on [active links](Active-Link-Detection) and [rendering attributes](Attributes#rendering-attributes) for more information. I'll be closing this now, but if you guys run into any issues or have any questions, don't hesitate to speak up!

**Comment by SergeyMiracle** [comment]
Great job :+1:

**Comment by asaf050** [comment]
Hey,
I need to add class to the parent UL if the link is active.
How can I check if item is active in the items loop?
Thanks!
