### ISSUE TITLE
Module Menus?

### ISSUE THREAD

**Issue by tankerkiller125** [caffeinated/menus#87]
I know that you have a modules repo. What I would like to do is build a unified admin page where all these modules can be controlled (there settings and what not). However I would also like to support 3rd part Modules. What this means is that I would like it so that each module can add on to a already defined menu when its loaded. Is there an easy way to do this?

**Comment by maisn3r** [comment]
This is pretty simple, in your global system you can make menu collection, then in each module you can call the collection via ::get() and add items.
