### ISSUE TITLE
Menu items with icons are auto-escaped

### ISSUE THREAD

**Issue by ikhrome** [caffeinated/menus#9]
Thank you very much, you made a great job and saved a lot of my time!

Just little correction for wiki in bootstrap template: we need to use `{!! $item->title !!}` to disable auto-escaping and now we can use icons.

So, the new template is:

``` php
@foreach($items as $item)
    <li @if($item->hasChildren())class ="dropdown"@endif>
        @if($item->link) <a @if($item->hasChildren()) class="dropdown-toggle" data-toggle="dropdown" @endif href="{{ $item->url() }}">
            {!! $item->title !!}
            @if($item->hasChildren()) <b class="caret"></b> @endif
        </a>
        @else
            {!! $item->title !!}
        @endif
        @if($item->hasChildren())
            <ul class="dropdown-menu">
                @foreach($item->children() as $child)
                    <li><a href="{{ $child->url() }}">{!! $child->title !!}</a></li>
                @endforeach
            </ul>
        @endif
    </li>
    @if($item->divider)
        <li{{\HTML::attributes($item->divider)}}></li>
    @endif
@endforeach
```

**Comment by otrishyn** [comment]
Template is just an example
Using icons it's great, but what about special chars or umlauts...
Every one corrects template for his needs :-)

**Comment by ikhrome** [comment]
@alexey-fut I know, that this is just an example :smile: I need to let someone to find a solution and not to get stuck, especially newbies.

**Comment by kaidesu** [comment]
Thanks for pointing this out. I added a note to the icons wiki page here https://github.com/caffeinated/menus/wiki/Icons
