### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by piperone** [caffeinated/menus#93]
Not much happening with issues on this repo it seems, but I still want to suggest Laravel 5.4 compatability. Thanks!

**Comment by kaidesu** [comment]
Readme hasn't been updated, but support for 5.4 was pushed today actually!

**Comment by piperone** [comment]
Cool! But you should also update the composer.json file as well. It still requires laravel 5.3-stuff.

**Comment by kaidesu** [comment]
D'oh! Sorry, thought this was in the `caffeinated/modules` repository. Re-opening this~

**Comment by yajra** [comment]
👍 waiting for L5.4 support too. Thanks!

**Comment by piperone** [comment]
Awesome! Thanks!
