### ISSUE TITLE
Instalation laravel 5.5.3

### ISSUE THREAD

**Issue by asselta** [caffeinated/menus#97]
I have problem with installation caffeinated/menus in fresh project Laravel 5.5.3 via composer.
After composer command "composer require caffeinated/menus" occur 1 problem:

`- caffeinated/menus v3.0 requires laravelcollective/html 5.3.* -> satisfiable by laravelcollective/html[5.3.x-dev, v5.3.0, v5.3.1, v5.3.2] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.3
    - Installation request for caffeinated/menus ^3.0 -> satisfiable by caffeinated/menus[v3.0, v3.0.1].
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - caffeinated/menus v3.0.1 requires illuminate/view 5.3.*|5.4.* -> satisfiable by illuminate/view[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/view v5.4.0|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.13|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.17|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.19|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.27|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.36|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.4.9|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.3.0|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.3.16|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.3.23|don't install laravel/framework v5.5.0
    - don't install illuminate/view v5.3.4|don't install laravel/framework v5.5.0
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.2, v5.5.3].
`

**Comment by benchpilot** [comment]
It's been fixed in the dev version. Just run composer require caffeinated/menus=3.0.x-dev and it should work.

**Comment by asselta** [comment]
That's works
Thank you Goldenblum

**Comment by yajra** [comment]
@kaidesu please tag to fix this issue. Thanks!

**Comment by kaidesu** [comment]
Tagged 3.0.2 with Laravel 5.5 support~
